# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: infra-exporter
    static_configs:
      - targets: ["localhost:9100"]
