{{/*
SPDX-License-Identifier: MIT
Copyright (c) 2026 Chris <goabonga@pm.me>
*/}}
{{- $root := . -}}
{{- range $name, $c := .Values.components }}
{{- if and $c.enabled $c.service.enabled $c.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" $root }}-{{ $name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "infra.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $c.service.type }}
  ports:
    - name: http
      port: {{ $c.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "infra.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
